stages:
  - build
  - deploy-staging
  - deploy-production

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
    - docker:23.0.6-dind

build:
  stage: build
  tags:
    - docker
  image: docker:stable
  before_script:
    - apk add --no-cache docker-compose
    - docker info
  script:
    - cd src
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose build

.deploy:
  tags:
    - docker
  image: 
     name: bitnami/kubectl:latest
     entrypoint: [""]
  before_script:
    - kubectl config get-contexts
    - kubectl config use-context ezlab/kubernetes-agent:leo

deploy_staging:
  stage: deploy-staging
  extends: .deploy
  environment:
        name: staging
        url: https://whunter.box.ezlab.ru
  script:
    - kubectl cluster-inf

deploy_production:
  stage: deploy-production
  extends: .deploy
  environment:
        name: production
        url: https://whunter.ezlab.ru
  only:
    - main
  script:
    - kubectl cluster-info